version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    groups:
      clap:
        patterns:
          - "clap*"
      config:
        patterns:
          - "serde"
          - "toml"
      logging:
        patterns:
          - "env_logger"
          - "log"
