---
name: Tag

permissions:
  contents: write

on:
  # Only run the workflow for pushes to the default branch.
  push:
    branches:
      - main

  # Allow the workflow to be triggered manually from the Actions tab.
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # https://stackoverflow.com/a/77680570/978961
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.extract-version.outputs.VERSION }}',
              sha: context.sha
            })
